name: Deploy Multi App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Latest Code
        run: |
          cd ~/projects
          git pull origin main

      - name: Deploy Containers
        run: |
          cd ~/projects
          docker-compose down
          docker-compose up --build -d
